server:
  port: 8080
  error:
    include-exception: true     # ??? exception? ??? ???? ??
    path: '/error'               # ??? ??? Handler? ??
    whitelabel:
      enabled: true             # ?? ?? ??? ????? ??? ?? ??? ?? ??

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource: # DATABASE
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_NM}
    password: ${DB_PW}

  jpa: # JPA
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

# 이미지 파일 저장 경로
file:
  upload-dir: src/main/resources/static/images/

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1시간

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
